# Generated by Django 4.1.7 on 2024-01-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Sage', models.IntegerField()),
                ('Smobile', models.CharField(max_length=10)),
            ],
        ),
    ]
